
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/team03-s23-5pm-2
owner: ucsb-cs156-s23
repo_name: team03-s23-5pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjY0ODczNzQ2","is_bot":false,"login":"cherylstanley","name":"Cheryl Stanley"},"headRefName":"Cheryl-EnergyDrinks","number":23,"title":"Cheryl Energy Drinks frontend files","url":"https://github.com/ucsb-cs156-s23/team03-s23-5pm-2/pull/23"},{"author":{"id":"MDQ6VXNlcjU5NjY0ODg0","is_bot":false,"login":"LeonFeng0325","name":""},"headRefName":"Leon-change-frontend-to-use-java-backend","number":21,"title":"Leon change frontend to use java backend","url":"https://github.com/ucsb-cs156-s23/team03-s23-5pm-2/pull/21"}]
